name: Expo Go
on:
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: yarn global add detox-cli
      - run: yarn eject
