name: Expo Go
on:
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: npm install -g detox-cli
      - run: npm install --global expo-cli
      - run: yarn downloadExpoApp
      - run: yarn ios
      - run: yarn test
